WIP: migrate to govuk frontend v3
alphagov/digitalmarketplace-buyer-frontend pull request #1106
Opened 2020-11-10 16:20 UTC by domoscargin

2020-11-23 15:22 UTC, lfdebrux commented
### My review checklist

I've:

- [ ] looked at the code
- [ ] tested locally
- [ ] run functional tests locally

2020-11-23 16:50 UTC, lfdebrux approved these changes
Amazing stuff. This was really easy to review because of all the detail in the commit messages, thanks for that.

As far as I can tell everything is working just dandy, I think we should 🚢 it to preview 👍

2020-11-23 16:57 UTC, lfdebrux requested changes
Spotted a problem, the error summary ids need to be updated for radios in tell us about contract journey.

Edited to add: I think we need to copy these lines from briefs-frontend to get the error summary links to work

https://github.com/alphagov/digitalmarketplace-briefs-frontend/blob/e4436f247bcf0bb73f12d810733489312a0c6026/config.py#L85-L88

2020-11-23 17:31 UTC, lfdebrux commented
Another issue I've found, the conditional reveal doesn't seem to work for save a new search page.

<img width="937" alt="Screenshot 2020-11-23 at 17 30 14" src="https://user-images.githubusercontent.com/503614/99994890-8fcd7480-2db1-11eb-9932-0272f5ee87fc.png">

2020-11-23 17:39 UTC, domoscargin commented
> https://github.com/alphagov/digitalmarketplace-briefs-frontend/blob/e4436f247bcf0bb73f12d810733489312a0c6026/config.py#L85-L88

Hmm, I don't think this will work since it's all WTForm-based rather than content loader. But Briefs has a couple of instances where the `get_errors_from_wtforms` method is working with error summary, so I'll investigate that.

2020-11-23 17:42 UTC, lfdebrux commented
> > https://github.com/alphagov/digitalmarketplace-briefs-frontend/blob/e4436f247bcf0bb73f12d810733489312a0c6026/config.py#L85-L88
> 
> Hmm, I don't think this will work since it's all WTForm-based rather than content loader. But Briefs has a couple of instances where the `get_errors_from_wtforms` method is working with error summary, so I'll investigate that.

Ah right; that's why I couldn't get it working 😁 

In that case I think we just hardcode it.

2020-11-24 09:46 UTC, domoscargin commented on app/main/forms/direct_award_forms.py
> +        id="input-save_search_selection",
I would've flailed a bit before finding this solution! 👏

2020-11-24 09:49 UTC, domoscargin commented
Thanks for these, @lfdebrux 

All looks good for me and passes locally.

2020-11-24 09:50 UTC, lfdebrux approved these changes

2020-11-24 09:56 UTC, merged